In [1]:
import numpy as np
import pandas as pd
from src.si.io.csv import read_csv
from src.si.data.dataset import Dataset

In [2]:
#1.1
#carregar ficheiro iris
data = read_csv("C:/Users/sonia/SIB/datasets/iris.csv", sep=',', features=True, label=True)

In [3]:
#1.2
#selecciona a primeira variável independente
print("Exercicio 1.2")
first_independent_variable = data.X[0]
print(first_independent_variable)

Exercicio 1.2
[5.1 3.5 1.4 0.2]


In [4]:
#verifica a dimensão do array resultante
print(first_independent_variable.shape)

(4,)


In [6]:
#1.3
#seleciona as últimas 5 amostras do iris dataset
print("Exercicio 1.3")
last_five = data.X[-5:]
print(last_five)

Exercicio 1.3
[[6.7 3.  5.2 2.3]
 [6.3 2.5 5.  1.9]
 [6.5 3.  5.2 2. ]
 [6.2 3.4 5.4 2.3]
 [5.9 3.  5.1 1.8]]


In [12]:
#qual a média das últimas 5 amostras para cada variável independente/feature
#perceber quais são as variáveis
data_features = data.features[:-1]
print(data_features)
means = data.X[-5:,].mean(axis=0)
#axis = 0 -> média por coluna, axis = 1 -> média por linha
print(means)
#media para cada feature, considerando cinco ultimas amostras

['sepal_length', 'sepal_width', 'petal_length']
[6.32 2.98 5.18 2.06]


In [13]:
#1.4
#seleciona todas as amostras do dataset com valor superior ou igual a 1 para todas as features
print("Exercicio 1.4")
arr = data.X
mask14 = np.all(arr[:,] >= 1, axis = 1)
sol_arr = arr[mask14]
print(sol_arr.shape)
print(sol_arr)

Exercicio 1.4
(100, 4)
[[7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]
 [5.7 2.8 4.5 1.3]
 [6.3 3.3 4.7 1.6]
 [4.9 2.4 3.3 1. ]
 [6.6 2.9 4.6 1.3]
 [5.2 2.7 3.9 1.4]
 [5.  2.  3.5 1. ]
 [5.9 3.  4.2 1.5]
 [6.  2.2 4.  1. ]
 [6.1 2.9 4.7 1.4]
 [5.6 2.9 3.6 1.3]
 [6.7 3.1 4.4 1.4]
 [5.6 3.  4.5 1.5]
 [5.8 2.7 4.1 1. ]
 [6.2 2.2 4.5 1.5]
 [5.6 2.5 3.9 1.1]
 [5.9 3.2 4.8 1.8]
 [6.1 2.8 4.  1.3]
 [6.3 2.5 4.9 1.5]
 [6.1 2.8 4.7 1.2]
 [6.4 2.9 4.3 1.3]
 [6.6 3.  4.4 1.4]
 [6.8 2.8 4.8 1.4]
 [6.7 3.  5.  1.7]
 [6.  2.9 4.5 1.5]
 [5.7 2.6 3.5 1. ]
 [5.5 2.4 3.8 1.1]
 [5.5 2.4 3.7 1. ]
 [5.8 2.7 3.9 1.2]
 [6.  2.7 5.1 1.6]
 [5.4 3.  4.5 1.5]
 [6.  3.4 4.5 1.6]
 [6.7 3.1 4.7 1.5]
 [6.3 2.3 4.4 1.3]
 [5.6 3.  4.1 1.3]
 [5.5 2.5 4.  1.3]
 [5.5 2.6 4.4 1.2]
 [6.1 3.  4.6 1.4]
 [5.8 2.6 4.  1.2]
 [5.  2.3 3.3 1. ]
 [5.6 2.7 4.2 1.3]
 [5.7 3.  4.2 1.2]
 [5.7 2.9 4.2 1.3]
 [6.2 2.9 4.3 1.3]
 [5.1 2.5 3.  1.1]
 [5.7 2.8 4.1 1.3]
 [6.3 3.3 6.  2.5]
 [5.8 2.

In [26]:
#1.5
#seleciona todas as amostras com a classe/label igual a ‘Iris-setosa’
print("Exercicio 1.5")
arr = data.X
mask_setosa = (data.y =="Iris-setosa")
new_arr = arr[mask_setosa]
print("New array - Iris-setosa")
print(new_arr)
#quantas amostras obténs?
print(len(new_arr))

Exercicio 1.5
New array - Iris-setosa
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]]
50


In [13]:
#2 - tentativa para testar os métodos do exercicio2
print("Exercicio 2")
data2 = read_csv("C:/Users/sonia/SIB/datasets/iris_missing_data.csv", sep=',', features=True, label=True)
#tamanho do dataset original
sh = data2.shape()
print(sh)
#retirar os NAs
remove_na = data2.dropna()
sa = data2.shape()
print(sa)

Exercicio 2
(150, 4)
(134, 4)


In [7]:
data3 = read_csv("C:/Users/sonia/SIB/datasets/iris_missing_data.csv", sep=',', features=True, label=True)
print(data3.summary())
#substituir NA por valor
fn = data3.fillna(value = -20)
#print(data3.X)
print(data3.summary())

        sepal_length  sepal_width  petal_length  petal_width
mean        5.839041     3.049655      3.746259     1.213793
median      5.800000     3.000000      4.300000     1.300000
min         4.300000     2.000000      1.000000     0.100000
max         7.900000     4.200000      6.900000     2.500000
var         0.697311     0.177534      3.144255     0.575258
        sepal_length  sepal_width  petal_length  petal_width
mean          5.1500     2.281333      3.271333     0.506667
median        5.7000     3.000000      4.250000     1.300000
min         -20.0000   -20.000000    -20.000000   -20.000000
max           7.9000     4.200000      6.900000     2.500000
var          18.0081    17.290852     14.133512    15.056889
